version: '3.6'

services:
  server:
    restart: always
    build: ./server
    volumes:
      - ./server:/usr/src/server
      - /usr/src/server/node_modules
    environment:
      SERVER_PORT: ${SERVER_PORT}
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TOKEN_SECRET: ${TOKEN_SECRET}
    ports:
      - 8765:8765
    depends_on:
      - db

  db:
    restart: always
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/db-data:/var/lib/mysql
    environment:
      SERVER_PORT: ${SERVER_PORT}
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  benchmark:
    build: ./benchmark
    depends_on:
      - server
    tty: true
    environment:
      SERVER_PORT: ${SERVER_PORT}
    command: "--url http://server:${SERVER_PORT} --request_interval 2 --prom_server_port 8001 --maze_size 1000 --verbose"
    ports:
      - 8001:8001

  parsec:
    image: spirals/parsec-3.0
    depends_on:
      - server
    tty: true
    command: "-a run -i native -S parsec -p ferret -n 6"
