---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: mazes-benchmark
    labels:
        app: mazes-benchmark
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mazes-benchmark
    template:
        metadata:
            name: mazes-benchmark
            labels:
                app: mazes-benchmark
        spec:
            containers:
            - name: mazes-benchmark
              image: aorfanou/mazes_benchmark
              imagePullPolicy: IfNotPresent
              args:
              - "--url http://mazes-backend:$(SERVER_PORT)"
              - "--maze_size 15"
              - "--subprocesses 5"
              - "--verbose"
              envFrom:
                  - configMapRef:
                      name: app-conf
