apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thesis

images:
  - name: aorfanou/mazes_backend
    newName: aorfanou/mazes_backend
    newTag: latest
  - name: aorfanou/mazes_benchmark
    newName: aorfanou/mazes_benchmark
    newTag: latest

resources:
  - namespace.yaml
  - app-config.yaml
  - backend.yaml
  - adminer.yaml
  - mysql.yaml
  - stress_ng.yaml
  # - parsec.yaml

bases:
  - benchmark

configMapGenerator:
    - name: mysql-initdb
      files:
      - mysql-initdb-config.sql
    - name: mysql-initdb-mazes
      files:
      - db-data/init_mazes.txt
    - name: mysql-initdb-users
      files:
      - db-data/init_users.txt
