apiVersion: apps/v1
kind: Deployment
metadata:
  name: parsec
  labels:
    app: parsec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parsec
  template:
    metadata:
      name: parsec
      labels:
        app: parsec
    spec:
      containers:

      - name: parsec
        imagePullPolicy: Always
        image: aorfanou/parsec
        securityContext:
          privileged: true
        args:
        - "-a run"
        - "-i native"
        - "-S parsec"
        - "-n 6"
        - "-p ferret,freqmine,blackscholes"
